name: Build GDevelop APK (Frontend + Backend)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build GDevelop Android APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código-fonte
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instalar Node.js e Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      # 3. Instalar dependências do projeto (Frontend)
      - name: Install frontend dependencies
        working-directory: newIDE/app
        run: |
          yarn install
          yarn build

      # 4. Configurar e compilar o Core (Backend)
      - name: Install CMake and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make libgl1-mesa-dev

      - name: Build GDevelop Core
        working-directory: Core
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)

      # 5. Preparar o APK (com Gradle)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        working-directory: newIDE/app
        run: |
          yarn add react-native
          cd android
          ./gradlew assembleDebug

      # 6. Upload do APK como artefato
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GDevelop-debug-APK
          path: newIDE/app/android/app/build/outputs/apk/debug/app-debug.apk
