name: Build GDevelop APK (Frontend + Backend)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build GDevelop APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instalação do Node.js e Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install frontend dependencies
        run: |
          cd newIDE/app
          yarn install
          yarn build

      # 3. Instalação de CMake e dependências do Core
      - name: Install CMake and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make libgl1-mesa-dev

      - name: Build GDevelop Core (Backend)
        run: |
          cd Core
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      # 4. Configuração do Java e Android SDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # 5. Build do APK com Gradle
      - name: Build APK
        run: |
          cd newIDE/app/android
          ./gradlew assembleDebug

      # 6. Upload do APK gerado
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GDevelop-debug-APK
          path: newIDE/app/android/app/build/outputs/apk/debug/app-debug.apk
